# Get All Books

GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

# Create a Book

POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
  "title": "hendyr ponter"
}

###

# Update a Book

PUT http://localhost:3001/books/2 HTTP/1.1
Content-Type: application/json

{
  "title": "harry potter"
}

###

# Delete a Book

DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json
